Solucao/Churrasco/Controllers/ChurrascoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Churrasco.Controllers
{
    public class ChurrascoController : Controller
    {
        // GET: Churrasco
        public ActionResult Index()
        {
            return View();
        }

        // GET: Churrasco/Details/5
        public ActionResult Details(int id)
        {
            if (id == null || id == 0)
            {
                RedirectToAction("Index", "Home");
            }

            var churrasco = new DAB.BO.Churrasco().BuscaPorID(id);

            if (churrasco == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return View(churrasco);
        }

        // GET: Churrasco/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Churrasco/Create
        [HttpPost]
        public ActionResult Create(DAB.DTO.Churrasco churrasco)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    new DAB.BO.Churrasco().Adiciona(churrasco);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View(churrasco);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Erro", "Erro ao salvar o novo churrasco tchê: " + ex.Message);
                return View(churrasco);
            }
        }

        // GET: Churrasco/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Churrasco/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Churrasco/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Churrasco/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Solucao/Churrasco/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Churrasco.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            var churrascos = new DAB.BO.Churrasco().Listar.OrderBy(c => c.Quando);
            return View(churrascos);
        }

        public ActionResult Create()
        {
            return View();
        }
    }
}

Solucao/Churrasco/Views/Churrasco/Create.cshtml
@model DAB.DTO.Churrasco

@{
    ViewBag.Title = "Criando seu Churras";
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Churras da Trinca
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="~/Home"><i class="fa fa-dashboard"></i> Home</a>
        </li>

    </ol>
</section>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Criar seu churras</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Quando, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quando, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quando, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Porque, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Porque, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Porque, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecoSugeridoSemBebida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecoSugeridoSemBebida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecoSugeridoSemBebida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecoSugeridoComBebido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecoSugeridoComBebido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecoSugeridoComBebido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorArrecadado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorArrecadado, new { htmlAttributes = new { @class = "form-control", disabled = "true" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="submit" value="Criar"  class="btn btn-default"/>
            </div>
        </div>
    </div>
}


@section scripts{
    <script src="~/Scripts/jquery.mask.min.js"></script>
    <script>
        $(document).ready(function () {

            //$('#Quando').mask('00/00/0000');
            $('#PrecoSugeridoSemBebida,#PrecoSugeridoComBebido').mask('000.000.000.000.000,00', { reverse: true });

            $('#Criar').click(function () {

                var form = $('#id do section form').closest("form");
                $.ajax({
                    type: 'POST',
                    url: '/Churrasco/Create/',
                    data: form.serialize(),
                    success: function (response) {
                        $('#id do seu alerta').fadeIn();

                        setTimeout(function () {
                            $('#alertSucesso').fadeOut();
                        }, 5000);

                    },
                });

            });



        });




    </script>
}

Solucao/Churrasco/Views/Churrasco/Details.cshtml
@model DAB.DTO.Churrasco

@{
    ViewBag.Title = "Details";
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Detalhes do churras, tchê!
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="~/Home"><i class="fa fa-dashboard"></i> Home</a>
        </li>
        <li>
            <a href="~/Churrasco" class="active">Churrasco</a>
        </li>

    </ol>
</section>


<div class="form-horizontal">
    <hr />
    @Html.HiddenFor(model => model.Id)

    <div class="form-group col-md-12">
        <label>Dia:</label>
        <blockquote>@Model.Quando.ToString("dd/MM/yyyy")</blockquote>
    </div>

    <div class="form-group col-md-12">
        <label>Porque?</label>
        <blockquote>@Model.Porque</blockquote>
    </div>


    <div class="form-group col-md-12">
        <label>Quantos pila?</label>
        <blockquote>
            Com bebida: @Model.PrecoSugeridoComBebido.ToString("C")
        </blockquote>
        <blockquote>
            Sem bebida @Model.PrecoSugeridoSemBebida.ToString("C")
        </blockquote>
    </div>


    <hr />
    <div id="actions" class="row">
        <div class="col-md-12 text-right">
            <input type="button" id="adicionarParticipante" value="+ Adicionar participante" class="btn btn-primary" />
        </div>
    </div>

</div>

<br />


<style>
    .ident-pago {
        text-indent: 50px;
    }
</style>

<div class="form-horizontal" style="border: 1px solid black">
    <div class="form-group col-md-12">
        <table class="table table-hover">
            <tbody>
                <tr>
                    <th scope="row">Número de Participantes:</th>
                    <td>0</td>
                </tr>
                <tr>
                    <th scope="row">Valor a ser arrecadado:</th>
                    <td>0</td>
                </tr>
                <tr>
                    <th scope="row">Valor já pago:</th>
                    <td>0</td>
                </tr>
                <tr class="ident-pago">
                    <th scope="row ">Total de Bebuns:</th>
                    <td>0</td>
                </tr>
                <tr class="ident-pago">
                    <th scope="row">Total de Saudáveis:</th>
                    <td>0</td>
                </tr>


            </tbody>
        </table>

    </div>
</div>


<!-- Modal Adicionar Participante -->
<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalLabel">Excluir Item</h4>
            </div>
            <div class="modal-body">
                Deseja realmente excluir este item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Sim</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">N&atilde;o</button>
            </div>
        </div>
    </div>
</div> <!-- /.modal -->

Solucao/Churrasco/Views/Home/Index.cshtml
@model IEnumerable<DAB.DTO.Churrasco>


@{
    ViewBag.Title = "Churrasco - Oba, coisa boa!";
}





<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Churras da Trinca
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="~/Home"><i class="fa fa-dashboard"></i> Home</a>
        </li>
    

    </ol>
</section>


<!-- Main content -->
<section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-lg-12 col-md-12  col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Opções</h3>
                </div>
                <div class="box-body">
                    <a href="~/Churrasco/Create" class="btn btn-primary">Adicionar churras</a>
                </div>
            </div>
        </div>

        <div class="col-lg-12 col-md-12  col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Listagem de Churrasco</h3>
                </div>
                <div class="box-body table-responsive no-padding">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Quando)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Porque)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ValorArrecadado)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Quando)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Porque)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ValorArrecadado)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Detalhes", "Details", "Churrasco", new { id = item.Id }, new { @class = "btn  btn-success btn-sm" }) 
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
        <!-- ./col -->
    </div> <!-- close row -->
</section> <!-- close section -->

Solucao/Churrasco/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Churras da Trinca", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Churras da Trinca</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    
    @RenderSection("scripts", false)

</body>
</html>